### ISSUE TITLE
Clearer directions for a newbie?

### ISSUE THREAD

**Issue by lamenramen** [steipete/SDURLCache#12]
Hi,

I am not seeing any caching behavior. I have set my request's caching policy to NSURLRequestReturnCacheDataElseLoad as well.

Can you update the documentation to make it more clear where we need to alloc init the SDURLCache object? I assume that it's in viewDidLoad or right before an NSURLRequest is made?

Thanks

**Comment by steipete** [comment]
No, it should be done in appDidFinishLaunching - just once per app.

**Comment by lamenramen** [comment]
Thank you so much!
