### ISSUE TITLE
Cached responses don't get removed when the resource expires

### ISSUE THREAD

**Issue by blach** [steipete/SDURLCache#14]
Hi Peter,

the method `storeCachedResponse: forRequest:` does look at the response headers and can detect an `Expires` header. If the resource doesn't expire within a certain amount of time, the response will be cached.

But, it seems like the expiration date is ignored after that. Shouldn't the expiration date be saved with the cached response and the cached response be deleted/ignored as soon as the expiration date is reached? 

Currently, it looks like cached responses are only removed when the cache size limit is reached.

I was wondering if I was maybe missing something?

Thanks,

Alexander

**Comment by steipete** [comment]
Yep, that's the case. Note that this is only a FORK of rs'es SDURLCache. This part of the design is not from me.

I suggest that you just stop using SDURLCache, as NSURLCache now caches on disk (and properly manages metadata in his sqlite file) http://petersteinberger.com/blog/2012/nsurlcache-uses-a-disk-cache-as-of-ios5/

**Comment by blach** [comment]
I know it's a fork - but one that is linked to by the AFNetworking FAQ at https://github.com/AFNetworking/AFNetworking/wiki/AFNetworking-FAQ. 

I was looking for a solution that works on iOS 4. 

I just wanted to ask before I either use our old, non-elegant, manual solution instead of NSURLCache or extend SDURLCache.

Thanks for clarifying how it currently works!

**Comment by blach** [comment]
Sorry, I should probably have posted this issue at rs's original github repository.

**Comment by blach** [comment]
Actually, I think it's already answered in this issue: https://github.com/rs/SDURLCache/issues/9

It seems like NSURLRequest does handle expired items after it is returned by the cache.
